### ISSUE TITLE
class based model syntax

### ISSUE THREAD

**Issue by bencao** [freewheel/modulajs#5]
## Description

A class based syntax to declare model, similar to React component class syntax.

createModel can still be supported. But being able to extend from Model directly will bring a lot of user land opportunities.

### Info

An example:

```
import { Model } from 'modula-next';

const ActionTypes = {
  INCREMENT: 'COUNTER_INCREMENT',
  DECREMENT: 'COUNTER_DECREMENT'
};

class CounterModel extends Model {
  sendIncrement() {
    this.dispatch({ type: ActionTypes.INCREMENT });
  }

  recvIncrement() {
    return {
      type: ActionTypes.INCREMENT,
      update(model) {
        const newModel = model.set('value', model.get('value') + 1);

        return [newModel];
      }
    };
  }

  sendDecrement() {
    this.dispatch({ type: ActionTypes.DECREMENT });
  }

  recvDecrement() {
    return {
      type: ActionTypes.DECREMENT,
      update(model) {
        const newModel = model.set('value', model.get('value') - 1);

        return [newModel];
      }
    };
  }
}

CounterModel.actionTypes = ActionTypes;
CounterModel.defaultProps = { value: 0 };

export default CounterModel;
```

**Comment by robinyy** [comment]
When @yiwsong investigated the extendability of the Model, he was struggling a lot with the direction of FP or OO. We did several discussions in the team and chose the former one because as an internally used library in FW, we want to shift the balance to abstraction over flexibility, for a better maintenance among hundreds of developers in the same project.

For the open source version, we may want to adjust the balance accordingly but alter/wrap it inside FW.

**Comment by bencao** [comment]
close since it's implemented in the **next** branch.
